status_by_color:
  "#FFFFFF": work
  "#808080": wait
  "#CCCCCC": wait
  "#B6D7A8": done
  "#D9D1E9": pre_done

palette:
  white: "#FFFFFF"
  dark_gray: "#909090"
  med_gray: "#C0C0C0"
  gray: "#E0E0E0"
  light_gray: "#F0F0F0"
  green: "#B6D7A8"
  light_green: "#D9EAD3"
  purple: "#D9D1E9"
  deep_purple: "#9f65cc"
  black: "#000000"

project_aliases:
  "Звезды в Африке": "ЗВА"
  "Ярче звезд": "ЯЗ"
  "Ярче Звезд": "ЯЗ"
  "Шоу Воли": "ШВ"
  "Битва Пикников": "БП"
  "Лига городов": "ЛГ"
  "Comedy Club": "CC"
  "Женский StandUp": "ЖC"
  "Женский стендап": "ЖC"
  "Большой куш": "Б КУШ"
  "Музыкальная интуиция": "МУЗ ИНТ"
  "Время завтрака!": "ЗАВТРАК"
  "По эфиру": "ЭФИР"
  "Сокровища императора": "СОКР ИМП"
  "Сокровища Императора ": "СОКР ИМП"
  "Выжить в Самарканде": "САМАРКАНД"
  "Наша Раша": "НР"
  "Конфетка": "КОНФ"
  "АЛЬФАБАНК": "АЛЬФА"
  "МОСКОВСКИЙ КАРТОФЕЛЬ": "МОСКАР"
  "КАПИТАН ВКУСОВ": "КАПИТАН"
  "Капитан вкусов": "КАПИТАН"
  "Битва экстрасенсов": "Б_ЭКСТР"
  "Выжить в Стамбуле ": "СТАМБУЛ"
  "Выжить в Стамбуле": "СТАМБУЛ"
  "Вологодский пломбир": "Пломбир"

hidden_stage_names:
  - ответ
  - эфир
  - тракт
  - _
  - съемка
  - старт
